### ISSUE TITLE
Switching to C++14?

### ISSUE THREAD

**Issue by offa** [mattgodbolt/seasocks#79]
What about switching to C++14 (eg. in form the of _seasocks v1.4_)? 

C++14 is now widely adopted and supported. Furthermore, GCC uses it as default since GCC6 and Clang will also do so from Clang6 onwards. Pretty much every OS should have at least GCC5 (respectively capable Clang) somehow available too.

----------------------------------

### Todo

- [x] Enable C++14 on *master*
- [x] Tag and release current HEAD as v1.3.2
- [x] Add a note, that v1.4.x will require C++14
- [x] Review supported compiler

**Comment by mattgodbolt** [comment]
Absolutely. I see no reason not to...though I know one user internal to the
company I work for is stuck on an old GCC. I'm happy to move forward (C++17
is now ratified!), and leave them on v1.3 for now. Feel free to upgrade, or
I'll look in to when I have time.

**Comment by offa** [comment]
Perfect! So I'll create a release of the current  Head as *v1.3.2* and upgrade *master* to C++14.

**Comment by offa** [comment]
That's it! Just one thing I can't to: Updating the Topics and replace `cpp11` with `cpp14`.

**Comment by mattgodbolt** [comment]
Topics updated! Thanks so much!
